apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: votingdb
  DATABASE_URL: postgresql://user:password@postgres:5432/votingdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432