services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votingdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d votingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/votingdb
      SECRET_KEY: supersecretkey123
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  voting-service:
    build: ../voting-service
    container_name: voting-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/votingdb
      SECRET_KEY: supersecretkey123
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  analytics-service:
    build: ../analytics-service
    container_name: analytics-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/votingdb
      SECRET_KEY: supersecretkey123
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - voting-service
      - analytics-service
    restart: always

volumes:
  pgdata: